analytics: {}
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.657692
  lightness: 0.114349
  rhythmicContrast: 0.982692
  saturation: 0.799038
cta: {}
layout_spectrum: 1
name: 'JK | Ethereal marketing that pays'
opengraph: {}
purpose: []
typography_spectrum: 0.809615
